_BASE_: "./YOLO-base.yaml"
MODEL:
  YAML: configs/yolov4-tiny.yaml
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedYOLO"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # WEIGHTS: "/app/twophase/checkpoint/R-50.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: build_darknet_backbone
  YOLO:
    FOCAL_LOSS_GAMMA: 0.0
    BOX_LOSS_GAIN: 0.05
    CLS_LOSS_GAIN: 0.3
    CLS_POSITIVE_WEIGHT: 1.0
    OBJ_LOSS_GAIN: 0.7
    OBJ_POSITIVE_WEIGHT: 1.0
    LABEL_SMOOTHING: 0.0
    ANCHOR_T: 4.0
    CONF_THRESH: 0.001
    IOU_THRES: 0.65
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  PIXEL_STD: [255.0, 255.0, 255.0]
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 100000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.04
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("bdd100k_day_train",) #voc_2012_train
  TRAIN_UNLABEL: ("bdd100k_night_train",) #Clipart1k_train
  TEST: ("bdd100k_night_val",) #Clipart1k_test
SEMISUPNET:
  Trainer: "studentteacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 50000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.3
  SUP_LOSS_WEIGHT: 1.0
  SCALE_LIST: (0.5, 0.6, 0.7,0.8,0.9,1.0)
  SCALE_STEPS: (57000,64000,71000,78000,85000,92000)
TEST:
  EVAL_PERIOD: 2000
NIGHTAUG: True
STUDENT_SCALE: True
CONSISTENCY: True